cft_testtask/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('wb/<path:link>', views.WhiteBlackPixels.as_view()),
	path('hex/<str:code>/<path:link>', views.HEXPixels.as_view()),
]

cft_testtask/cft_testtask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('api/', include('api.urls')),
	path('', include('pic_app.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cft_testtask/pic_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
	path('', main_view, name = 'index'),
	path('results_wb', results_wb, name = 'results_wb'),
	path('results_hex', results_hex, name = 'results_hex'),
]

cft_testtask/api/models.py
from django.db import models

# Create your models here.

cft_testtask/pic_app/models.py
from django.db import models

ANALYSIS_MODES = [
    ('WB', 'Черные vs Белые'),
    ('HEX', 'Цвет по HEX-коду'),
]

class Pictures(models.Model):
    # name = models.CharField(max_length=50)
    src = models.ImageField("Выберите картинку", upload_to='images/')
    mode = models.CharField("Режим", max_length=30, choices=ANALYSIS_MODES, default='HEX')
    color = models.CharField("Код цвета #", max_length=6, blank=True)

cft_testtask/pic_app/forms.py
from django import forms
from .models import *
  
class ImageForm(forms.ModelForm):
  
    class Meta:
        model = Pictures
        fields = ['src', 'mode', 'color']
        
        #self.src.label = "Выберите картинку"
        #self.mode.label = "Режим"
        #self.mode.color = "Код цвета #"

cft_testtask/api/views.py
from django.shortcuts import render
from rest_framework.response import Response
from .models import *
# from .serializers import *
from rest_framework import generics
from rest_framework.decorators import api_view

from rest_framework import views
from rest_framework.response import Response

from .pic_pix import *
from urllib.request import urlopen

from pathlib import Path
import os
from http.client import InvalidURL

class WhiteBlackPixels(views.APIView):
	def get(self, request, link):
		print(link)
		try:
			rez = white_black(urlopen('http://127.0.0.1:8000/media/'+link))
		except InvalidURL:
			rez = {"err": "Имена файлов не должны содержать проблелы"}
		
		return Response(rez)
		
class HEXPixels(views.APIView):
	def get(self, request, code, link):
		print(link)
		try:
			rez = hex_pix(urlopen('http://127.0.0.1:8000/media/'+link), code)
		except InvalidURL:
			rez = {"err": "Имена файлов не должны содержать проблелы"}	

		return Response(rez)

cft_testtask/pic_app/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import *
import requests


def main_view(request):
  
	if request.method == 'POST':
		form = ImageForm(request.POST, request.FILES)
  
		if form.is_valid():
			form.save()
			
			if form.cleaned_data['mode'] == 'WB':
				# This is not logical, I suppose, but it is enough for demonstration 
				results = requests.get('http://127.0.0.1:8000/api/wb/images/'+str(form.cleaned_data['src'])).json()
				request.session['temp_data'] = results
				
				return redirect('results_wb') 
			elif form.cleaned_data['mode'] == 'HEX':
				results = requests.get('http://127.0.0.1:8000/api/hex/'+str(form.cleaned_data['color'])+'/images/'+str(form.cleaned_data['src'])).json()
				results['color'] = '#'+str(form.cleaned_data['color'])
				request.session['temp_data'] = results
				
				return redirect('results_hex') 
			
	else: 
		
		print()
		form = ImageForm()
        	
	return render(request, 'index.html', {'form' : form})
  
  
def results_wb(request):
	print(request.session['temp_data'])
	r = request.session['temp_data']
	if 'err' not in r.keys():
		
		if r['which_is'] == "White":
			word = "белых"
		elif r['which_is'] == "Black":
			word = "чёрных"
		else:
			word = "и тех, и других"
		return HttpResponse("Количество белых пикселей: "+str(r['wpx'])+" ("+str(r['wper'])+"""%) <br> 
		Количество чёрных пикселей: """+str(r['bpx'])+" ("+str(r['bper'])+"""%) <br> 
		Больше всего """+word+"""<br>
		<a href="http://127.0.0.1:8000">Вернуться</a>
		""")
	else:
		return HttpResponse(r['err']+"""
		<br>
		<a href="http://127.0.0.1:8000">Вернуться</a>
		""")
		
def results_hex(request):
	print(request.session['temp_data'])
	r = request.session['temp_data']
	if 'err' not in r.keys():
		#return HttpResponse(str(r))
		return HttpResponse("Количество пикселей цвета "+str(r['color'])+": "+str(r['hexpix'])+" ("+str(r['hexper'])+"""%) <br> 
		<div style="background-color: """+ str(r['color'])+"""; ">
			<p>Фон этой строки окрашен в выбранный вами цвет</p>
		</div>
		<a href="http://127.0.0.1:8000">Вернуться</a>
		""")
	else:
		return HttpResponse(r['err']+"""
		<br>
		<a href="http://127.0.0.1:8000">Вернуться</a>
		""")

cft_testtask/pic_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image Analysis</title>
</head>
<body>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        <div align="center">
		<h3>Анализ пикселей</h3>
		{{ form.as_p }}
		<button type="submit">Загрузка файла</button>
		
		<h3>Как пользоваться этим приложением?</h3>
		<ul>
			<li>Данный веб-сервис позволит вам посчитать количество пикселей <br>заданного цвета</li>
			<li>Режим "Чёрные vs белые" подсчитает количество белых и чёрных <br>пикселей, а также сравнит их количество</li>
			<li>Режим "Цвет по HEX-коду" найдёт количество пикселей по <br>заданному вами цвету</li>
		</ul>
		
		<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
		  <script>
		    if ($('#id_mode').val() === 'WB'){
			  $('#id_color').hide();
			  $('label[for="id_color"]').hide();
			  
		      } else {
			  $('#id_color').show();
			  $('label[for="id_color"]').show();
		      }
		    $('#id_mode').change(function () {
		      var optionSelected = $("option:selected", this);
		      var valueSelected = $(this).val();
		      console.log(valueSelected);
		      if (valueSelected === 'WB'){
			  $('#id_color').hide();
			  $('label[for="id_color"]').hide();
			  
		      } else {
			  $('#id_color').show();
			  $('label[for="id_color"]').show();
		      }
		    });
		  </script>

        </div>
    </form>
</body>
</html>